name: Auto upload
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, edwin]
    outputs:
      jarFile: ${{ steps.publish.outputs.jarFile }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build on Maven
        run: mvn -f releaseservice/pom.xml install
      - name: Set Path file
        run: |
          dir /b releaseservice\target\*.jar >> jar.txt
          set /p jar=<jar.txt
        shell: cmd
      - id: publish
        run: |
          $filename = (Get-Content jar.txt)
          echo "jarFile=$filename" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
  upload:
    needs: build
    runs-on: [self-hosted, edwin]
    steps:
      - name: Upload to SV10 and SV20
        run: |
          sh -f "C:/Users/edwin.rosalesjuarez/Documents/shell/deploy.sh" -p releaseservice/target/${{needs.build.outputs.jarFile}} -t /DevOps/devops-rest-apis-main/v-0.0.1 -l "/c/Users/edwin.rosalesjuarez/Documents/shell/servers.txt"
          echo ${{needs.build.outputs.jarFile}}
          
          
