name: workflow_01
on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':Ashwini-Lokannavar'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':devops-rest-apis-postman' 

jobs:
  build:
    runs-on: [self-hosted, FactoryVm]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/:Ashwini-Lokannavar/:devops-rest-apis-postman/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.DEVOPSAPI_POSTMANKEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
