name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: Travelport-Enterprise/devops-rest-apis-postman/edit/main/.github/workflows/postamantest.yml

  
