name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: Travelport-Enterprise/devops-rest-apis-postman/.github/workflows/postamantest.yml@v1

  
