name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: Travelport-Enterprise/devops-rest-apis-postman/.github/workflows/postamantest.yml@main
    secrets:
      token: ${{ secrets.TESTING_POSTMAN }}

  
