name: Auto upload
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, FactoryVm]
    
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DEVOPSAPI_POSTMANKEY }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DEVOPSAPI_POSTMANKEY }}
        branch: 'source'    # default using 'master', change it if you want to push to another branch
